version: "3.9"
services:
  db:
    container_name: db-tfinal
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tfinal_db
      MYSQL_USER: tfinal
      MYSQL_PASSWORD: 123456
    networks:
      - net-tfinal
  web:
    container_name: web-tfinal
    depends_on:
      - db
    ports:
      - "8088:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-tfinal
networks:
  net-tfinal:
    
